//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CartEntities : DbContext
    {
        public DB_CartEntities()
            : base("name=DB_CartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCart> tCarts { get; set; }
        public virtual DbSet<tCartDetail> tCartDetails { get; set; }
        public virtual DbSet<tProduct> tProducts { get; set; }
        public virtual DbSet<tUser> tUsers { get; set; }
    }
}
