//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCart
    {
        public int cID { get; set; }
        public string cPayType { get; set; }
        public Nullable<int> cTotal { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
    }
}
