//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCartDetail
    {
        public int ciID { get; set; }
        public int ciProduct { get; set; }
        public Nullable<int> ciAmount { get; set; }
        public Nullable<int> ciPrice { get; set; }
    }
}
