//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tUser
    {
        public int uID { get; set; }
        public string uFullName { get; set; }
        [RegularExpression(@"[A-Za-z0-9]{6,20}")]
        [Required]
        public string uUsername { get; set; }
        [RegularExpression(@"[A-Za-z0-9!@#$%^&*()/*-+_=]{6,20}")]
        [Required]
        [DataType(DataType.Password)]
        public string uPassword { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Compare("uPassword")]
        public string ConfirmPassword { get; set; }
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        [Required]
        public string uEmail { get; set; }
        [Required]
        public string uPhone { get; set; }
        public Nullable<bool> uStatus { get; set; }
    }
}
